version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    # command: gunicorn snacks_api_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on: 
      - db
  db:
    image: postgres:11
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment: 
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres 
        POSTGRES_DB: postgres


volumes:
    postgres_data:


# run with runserver then docker then gunicorn then sql

