# Generated by Django 3.0.8 on 2020-07-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=500)),
                ('ingredients', models.TextField(max_length=2500)),
                ('steps', models.TextField(max_length=2500)),
                ('meal_type', models.CharField(max_length=16)),
                ('img_src_1', models.URLField(blank=True)),
                ('img_src_2', models.URLField(blank=True)),
                ('img_src_3', models.URLField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
