# Generated by Django 3.0.8 on 2020-07-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img_src_1',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img_src_2',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img_src_3',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
